<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class VideoCut extends Model
{
    use HasFactory;
    protected $guarded = [];
    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($video) {
            $video->id = (string) Str::uuid();
        });
    }

    public function video(){
        return $this->belongsTo(Video::class);
    }

    public function video_conversions(){
        return $this->hasMany(VideoConversion::class);
    }
}
